org: tomwaite
app: text-improve
service: flask-api

provider:
  name: aws
  runtime: python3.7
  region: eu-west-3

functions:
  generateText:
    handler: handler.lambda_generate_text
    memorySize: 3008
    timeout: 30
    warmup: true
    events:
      - http:
          path: predict
          method: post
          cors: true

package:
  individually: false
  exclude:
    - package.json
    - package-log.json
    - node_modules/**
    - cache/**
    - test/**
    - __pycache__/**
    - .pytest_cache/**
    - model/pytorch_model.bin
    - raw/**
    - .vscode/**
    - .ipynb_checkpoints/**
    - scripts
    - app.py
    - __init__.py

custom:
  pythonRequirements:
    dockerizePip: true
    zip: true
    slim: true
    strip: false
    noDeploy:
      - docutils
      - jmespath
      - pip
      - python-dateutil
      - setuptools
      - six
      - tensorboard
    useStaticCache: true
    useDownloadCache: true
    cacheLocation: './cache'
  warmup:
    events:
      - schedule: 'rate(5 minutes)'
    timeout: 50

plugins:
  - serverless-python-requirements
  - serverless-plugin-warmup
