org: tomwaite
app: text-improve
service: flask-api

provider:
  name: aws
  runtime: python3.7
  region: eu-west-3

functions:
  generateText:
    handler: handler.lambda_handler
    memorySize: 3008
    timeout: 300
    warmup: true
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

custom:
  wsgi:
    app: app.app
    pythonBin: python3 # Some systems with Python3 may require this
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux

plugins:
  - serverless-wsgi
  - serverless-python-requirements
  - serverless-plugin-warmup
